inputFile: ${inputFile}
output-directory: ${outputDirectory}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    platform: hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver